/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * Productos.java
 */
package Interfaces;

import Conexion.conectar;
import java.awt.JobAttributes;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class Vehiculos extends javax.swing.JInternalFrame {

    DefaultTableModel tabla;

    /**
     * Creates new form Productos
     */
    public Vehiculos() {
        initComponents();
        cargarlistavehiculos("");

    }

//    public void calcular() {
//        String pre;
//        String can;
//        double iva = 0;
//        double total = 0;
//        double subtotal = 0;
//        double precio;
//        int cantidad;
//        double imp = 0.0;
//
//        /*can=Integer.parseInt(cant);
//            imp=pre*can;
//            dato[4]=Float.toString(imp);*/
//        for (int i = 0; i < Ventas.tbdet.getRowCount(); i++) {
//            pre = Ventas.tbdet.getValueAt(i, 5).toString();
//            can = Ventas.tbdet.getValueAt(i, 3).toString();
//            precio = Double.parseDouble(pre);
//            cantidad = Integer.parseInt(can);
//            imp = precio * cantidad;
//            subtotal = subtotal + imp;
//            iva = subtotal * 0.18;
//            total = subtotal + iva;
//            // txtcod.setText(""+Math.rint(c*100)/100)
//            Ventas.tbdet.setValueAt(Math.rint(imp * 100) / 100, i, 4);
//
//        }
//        Ventas.txtsubtotal.setText(Double.toString(subtotal));
//        Ventas.txtiva.setText("" + Math.rint(iva * 100) / 100);
//        Ventas.txttotal.setText("" + Math.rint(total * 100) / 100);
//    }

    String comparar(String idveh) {
        String cant = "";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM vehiculos WHERE ID_VEH='" + idveh + "'");
            while (rs.next()) {
                cant = rs.getString(6);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Vehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
        return cant;

    }

    void cargarlistavehiculos(String dato) {
        String[] Titulo = {"Codigo", "Modelo", "Color", "Año", "Precio", "Stock"};
        tabla = new DefaultTableModel(null, Titulo);
        String[] Registro = new String[6];
        String mostrar = "SELECT * FROM vehiculos WHERE CONCAT(ID_VEH,'',ID_MOD_VEH) LIKE '%" + dato + "%'";
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(mostrar);
            while (rs.next()) {
                Registro[0] = rs.getString("ID_VEH");
                Registro[1] = rs.getString("ID_MOD_VEH");
                Registro[2] = rs.getString("COL_VEH_PER");
                Registro[3] = rs.getString("ANIO_VEH");
                Registro[4] = rs.getString("PRE_VEH");
                Registro[5] = rs.getString("STOCK");
                tabla.addRow(Registro);
            }
            tbvehic.setModel(tabla);
        } catch (SQLException ex) {
            Logger.getLogger(Vehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnenviarveh = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbvehic = new javax.swing.JTable();
        txtveh = new javax.swing.JTextField();
        btnmostrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        mnenviarveh.setText("Generar Venta");
        mnenviarveh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnenviarvehActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnenviarveh);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("PRODUCTOS");

        tbvehic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbvehic.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(tbvehic);

        txtveh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtvehKeyReleased(evt);
            }
        });

        btnmostrar.setText("Mostrar todo");
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar Productos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtveh, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnmostrar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnmostrar)
                    .addComponent(txtveh, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
// TODO add your handling code here:
    cargarlistavehiculos("");
}//GEN-LAST:event_btnmostrarActionPerformed

private void txtvehKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvehKeyReleased
// TODO add your handling code here:
    cargarlistavehiculos(txtveh.getText());
}//GEN-LAST:event_txtvehKeyReleased

private void mnenviarvehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnenviarvehActionPerformed
// TODO add your handling code here:

    try {

        DefaultTableModel tabladet = (DefaultTableModel) Ventas.tbdet.getModel();
        String[] dato = new String[6];

        int fila = tbvehic.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No  ha seleccionado ningun registro");
        } else {
            String idveh = tbvehic.getValueAt(fila, 0).toString();
            String modveh = tbvehic.getValueAt(fila, 1).toString();
            String colveh = tbvehic.getValueAt(fila, 2).toString();
            String anioveh = tbvehic.getValueAt(fila, 3).toString();
            String precioveh = tbvehic.getValueAt(fila, 4).toString();
            String stock = tbvehic.getValueAt(fila, 5).toString();
            int c = 0;
            int j = 0;
            String cant = JOptionPane.showInputDialog("ingrese cantidad");
            if ((cant.equals("")) || (cant.equals("0"))) {
                JOptionPane.showMessageDialog(this, "Debe ingresar algun valor mayor que 0");
            } else {

                int canting = Integer.parseInt(cant);
                int comp = Integer.parseInt(comparar(idveh));

                if (canting > comp) {
                    JOptionPane.showMessageDialog(this, "Ud. no cuenta con el stock apropiado");
                } else {
                    for (int i = 0; i < Ventas.tbdet.getRowCount(); i++) {
                        Object com = Ventas.tbdet.getValueAt(i, 0);
                       
                        if (idveh.equals(com)) {
                            j = i;
                            Ventas.tbdet.setValueAt(cant, i, 3);
                            c = c + 1;

                        }

                    }
                    if (c == 0) {
                       int totalcost = canting * Integer.valueOf(precioveh);
                        
                        dato[0] = idveh;
                        dato[1] = colveh;
                        dato[2] = precioveh;
                        dato[3] = cant;
                        dato[4] = String.valueOf(totalcost);

                        tabladet.addRow(dato);

                        Ventas.tbdet.setModel(tabladet);
                        //calcular();
                        //fac.calcular();
                    }
                }
                //  fac.calcular();
            }

        }

    } catch (Exception e) {
    }

}//GEN-LAST:event_mnenviarvehActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem mnenviarveh;
    private javax.swing.JTable tbvehic;
    private javax.swing.JTextField txtveh;
    // End of variables declaration//GEN-END:variables
conectar cc = new conectar();
    Connection cn = cc.conexion();
//Factura fac= new Factura();

}
